spring.application.name=sub_agent_synthetic_data
server.port= 8096
spring.main.web-application-type= reactive
spring.ai.openai.api-key= ${OPENAI_API_KEY}
spring.ai.openai.embedding.model= text-embedding-3-large
spring.ai.openai.responses.options.model= gpt-5.1
spring.ai.openai.chat.enabled= true
spring.ai.openai.chat.options.model= gpt-5.1
spring.ai.openai.chat.options.temperature=1.0
event.name-chat= new-message

logging.level.org.springframework.http.codec=DEBUG
spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG

